<a href="https://colab.research.google.com/github/himanshupant03/Dataanalysis/blob/main/spam/ham%20classification%20project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# this code witll detect the spam (1) or not spam (0)

In [3]:
import pandas as pd
import numpy as np 
import nltk 
from nltk.corpus import stopwords 
import  string

In [4]:
#loading the data 
from google.colab import files
uploaded = files.upload()


Saving spam_ham_dataset.csv to spam_ham_dataset.csv


In [5]:
#read the CSV files 
df = pd.read_csv("spam_ham_dataset.csv")
df.head(10)

Unnamed: 0  ... label_num
0         605  ...         0
1        2349  ...         0
2        3624  ...         0
3        4685  ...         1
4        2030  ...         0
5        2949  ...         0
6        2793  ...         0
7        4185  ...         1
8        2641  ...         0
9        1870  ...         0

[10 rows x 4 columns]

In [6]:
df.shape

(5171, 4)

In [7]:
df.columns

Index(['Unnamed: 0', 'label', 'text', 'label_num'], dtype='object')

In [8]:
df.drop_duplicates(inplace = True)

In [9]:
df.shape

(5171, 4)

In [10]:
df.isnull().sum()

Unnamed: 0    0
label         0
text          0
label_num     0
dtype: int64

In [12]:
#downlod the stopword package 
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [18]:
#processing the text
def process_test(text):
  #we are removing the stopwards , punctuations and other words which are useless , it then returns a list of clean words 
  nopunc = [char for char in text if char not in  string.punctuation]
  nopunc = ''.join(nopunc)

  clean_words = [word for word in nopunc.split() if word.lower not in stopwords.words('english')]

  return clean_words

In [19]:
#tokenization 
df['text'].head(10).apply(process_test)

0    [Subject, enron, methanol, meter, 988291, this...
1    [Subject, hpl, nom, for, january, 9, 2001, see...
2    [Subject, neon, retreat, ho, ho, ho, we, re, a...
3    [Subject, photoshop, windows, office, cheap, m...
4    [Subject, re, indian, springs, this, deal, is,...
5    [Subject, ehronline, web, address, change, thi...
6    [Subject, spring, savings, certificate, take, ...
7    [Subject, looking, for, medication, we, re, th...
8    [Subject, noms, actual, flow, for, 2, 26, we, ...
9    [Subject, nominations, for, oct, 21, 23, 2000,...
Name: text, dtype: object

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
message_bow = CountVectorizer(analyzer = process_test).fit_transform(df['text'])


In [23]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(message_bow , df['label_num'] ,test_size = 0.2 ,random_state = 0)


In [24]:
message_bow.shape

(5171, 50533)

In [25]:
  #using naive bayes classier 
  from sklearn.naive_bayes import MultinomialNB
  classfier = MultinomialNB().fit(X_train,y_train)
  

In [32]:
print(classfier.predict(X_train ))

print(classfier.predict(X_test))
print(y_test.values)

[0 0 0 ... 1 0 0]
[0 0 0 ... 0 1 0]
[0 0 0 ... 0 1 0]


In [33]:
#evaluation of the model 
from sklearn.metrics import classification_report , confusion_matrix , accuracy_score
pred = classfier.predict(X_train)
print(classification_report(y_train , pred))
print(confusion_matrix(y_train , pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      2940
           1       0.98      0.97      0.98      1196

    accuracy                           0.99      4136
   macro avg       0.99      0.98      0.98      4136
weighted avg       0.99      0.99      0.99      4136

[[2919   21]
 [  31 1165]]


In [34]:
print(accuracy_score(y_train , pred))

0.9874274661508704


In [35]:
pred1 = classfier.predict(X_test)
print(accuracy_score(y_test, pred1))
print(confusion_matrix(y_test , pred1))

0.9768115942028985
[[721  11]
 [ 13 290]]
